import sys
import os
import pandas as pd
import numpy as np

# Enterprise import paths
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
STRATEGY_CORE = os.path.abspath(os.path.join(CURRENT_DIR, "..", "core"))
sys.path.insert(0, STRATEGY_CORE)

from logger import OdysseyLogger

logger = OdysseyLogger('backtester')

class OdysseyBacktester:
    def __init__(self, initial_capital=100000.0, commission=3.0, slippage_pips=1.5):
        self.initial_capital = initial_capital
        self.capital = initial_capital
        self.commission = commission
        self.slippage_pips = slippage_pips
        
        self.trades = []
        self.equity_curve = [initial_capital]

    def load_data(self, csv_path: str) -> pd.DataFrame:
        """Load historical features generated by data-service or ml-engine testing script"""
        logger.info(f"Loading backtest data from {csv_path}")
        df = pd.read_csv(csv_path)
        if 'time' in df.columns:
            df['time'] = pd.to_datetime(df['time'])
            df.set_index('time', inplace=True)
        return df

    def run_vectorized_test(self, df: pd.DataFrame, signals: pd.Series):
        """
        Fast vectorized backtest.
        signals: Series of +1 (Buy), -1 (Sell), 0 (Hold) aligned with df index.
        """
        logger.info("Running vectorized backtest...")
        
        # Calculate daily returns of the asset
        df['returns'] = df['close'].pct_change()
        
        # Shift signals by 1 so we calculate return on the BAR AFTER the signal is generated
        df['strategy_returns'] = df['returns'] * signals.shift(1).fillna(0)
        
        # Calculate Equity
        df['cumulative_returns'] = (1 + df['strategy_returns']).cumprod()
        df['equity'] = self.initial_capital * df['cumulative_returns']
        
        self.equity_curve = df['equity'].tolist()
        
        # Store for reporting
        self.results_df = df
        return self.results_df

    def generate_report(self):
        """Print extensive performance report"""
        if not hasattr(self, 'results_df'):
            logger.error("Must run backtest before generating report!")
            return
            
        final_equity = self.equity_curve[-1]
        total_return = (final_equity - self.initial_capital) / self.initial_capital * 100
        
        # Max Drawdown
        roll_max = self.results_df['equity'].cummax()
        drawdown = self.results_df['equity'] / roll_max - 1.0
        max_drawdown = drawdown.min() * 100
        
        # Sharpe (assuming 0% risk free rate)
        strat_returns = self.results_df['strategy_returns']
        mean_ret = strat_returns.mean()
        std_ret = strat_returns.std()
        sharpe = (mean_ret / std_ret) * np.sqrt(252 * 24 * 60) if std_ret > 0 else 0 # Assuming 1M timeframe
        
        print("\n" + "="*40)
        print("📊 ODYSSEY V2 BACKTEST REPORT")
        print("="*40)
        print(f"Initial Capital : ${self.initial_capital:,.2f}")
        print(f"Final Capital   : ${final_equity:,.2f}")
        print(f"Total Return    : {total_return:+.2f}%")
        print(f"Max Drawdown    : {max_drawdown:+.2f}%")
        print(f"Sharpe Ratio    : {sharpe:.2f}")
        print("="*40 + "\n")

if __name__ == "__main__":
    backtester = OdysseyBacktester()
    # Dummy data generator for testing the backtester standalone
    dates = pd.date_range(start='2024-01-01', periods=1000, freq='1min')
    df = pd.DataFrame({
        'close': np.random.normal(1950, 5, 1000).cumsum() # Random walk
    }, index=dates)
    
    # Random signals (-1 to 1) 
    signals = pd.Series(np.random.choice([-1, 0, 1], size=1000), index=dates)
    
    backtester.run_vectorized_test(df, signals)
    backtester.generate_report()
