# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import strategy_pb2 as strategy__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in strategy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StrategyServiceStub(object):
    """==========================================
    Strategy Service
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateSignal = channel.unary_unary(
                '/strategy.StrategyService/GenerateSignal',
                request_serializer=strategy__pb2.SignalRequest.SerializeToString,
                response_deserializer=strategy__pb2.SignalResponse.FromString,
                _registered_method=True)
        self.GetActiveStrategies = channel.unary_unary(
                '/strategy.StrategyService/GetActiveStrategies',
                request_serializer=strategy__pb2.ActiveStrategiesRequest.SerializeToString,
                response_deserializer=strategy__pb2.ActiveStrategiesResponse.FromString,
                _registered_method=True)
        self.ActivateStrategy = channel.unary_unary(
                '/strategy.StrategyService/ActivateStrategy',
                request_serializer=strategy__pb2.ActivateStrategyRequest.SerializeToString,
                response_deserializer=strategy__pb2.ActivateStrategyResponse.FromString,
                _registered_method=True)
        self.DeactivateStrategy = channel.unary_unary(
                '/strategy.StrategyService/DeactivateStrategy',
                request_serializer=strategy__pb2.DeactivateStrategyRequest.SerializeToString,
                response_deserializer=strategy__pb2.DeactivateStrategyResponse.FromString,
                _registered_method=True)
        self.GetStrategyPerformance = channel.unary_unary(
                '/strategy.StrategyService/GetStrategyPerformance',
                request_serializer=strategy__pb2.PerformanceRequest.SerializeToString,
                response_deserializer=strategy__pb2.PerformanceResponse.FromString,
                _registered_method=True)
        self.ExplainSignal = channel.unary_unary(
                '/strategy.StrategyService/ExplainSignal',
                request_serializer=strategy__pb2.ExplainSignalRequest.SerializeToString,
                response_deserializer=strategy__pb2.ExplainSignalResponse.FromString,
                _registered_method=True)


class StrategyServiceServicer(object):
    """==========================================
    Strategy Service
    ==========================================
    """

    def GenerateSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveStrategies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStrategyPerformance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StrategyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSignal,
                    request_deserializer=strategy__pb2.SignalRequest.FromString,
                    response_serializer=strategy__pb2.SignalResponse.SerializeToString,
            ),
            'GetActiveStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveStrategies,
                    request_deserializer=strategy__pb2.ActiveStrategiesRequest.FromString,
                    response_serializer=strategy__pb2.ActiveStrategiesResponse.SerializeToString,
            ),
            'ActivateStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateStrategy,
                    request_deserializer=strategy__pb2.ActivateStrategyRequest.FromString,
                    response_serializer=strategy__pb2.ActivateStrategyResponse.SerializeToString,
            ),
            'DeactivateStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateStrategy,
                    request_deserializer=strategy__pb2.DeactivateStrategyRequest.FromString,
                    response_serializer=strategy__pb2.DeactivateStrategyResponse.SerializeToString,
            ),
            'GetStrategyPerformance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStrategyPerformance,
                    request_deserializer=strategy__pb2.PerformanceRequest.FromString,
                    response_serializer=strategy__pb2.PerformanceResponse.SerializeToString,
            ),
            'ExplainSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainSignal,
                    request_deserializer=strategy__pb2.ExplainSignalRequest.FromString,
                    response_serializer=strategy__pb2.ExplainSignalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'strategy.StrategyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('strategy.StrategyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StrategyService(object):
    """==========================================
    Strategy Service
    ==========================================
    """

    @staticmethod
    def GenerateSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strategy.StrategyService/GenerateSignal',
            strategy__pb2.SignalRequest.SerializeToString,
            strategy__pb2.SignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strategy.StrategyService/GetActiveStrategies',
            strategy__pb2.ActiveStrategiesRequest.SerializeToString,
            strategy__pb2.ActiveStrategiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strategy.StrategyService/ActivateStrategy',
            strategy__pb2.ActivateStrategyRequest.SerializeToString,
            strategy__pb2.ActivateStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeactivateStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strategy.StrategyService/DeactivateStrategy',
            strategy__pb2.DeactivateStrategyRequest.SerializeToString,
            strategy__pb2.DeactivateStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStrategyPerformance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strategy.StrategyService/GetStrategyPerformance',
            strategy__pb2.PerformanceRequest.SerializeToString,
            strategy__pb2.PerformanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strategy.StrategyService/ExplainSignal',
            strategy__pb2.ExplainSignalRequest.SerializeToString,
            strategy__pb2.ExplainSignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
