# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import trading_pb2 as trading__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trading_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradingServiceStub(object):
    """==========================================
    Trading Service
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMarketData = channel.unary_unary(
                '/trading.TradingService/GetMarketData',
                request_serializer=trading__pb2.MarketDataRequest.SerializeToString,
                response_deserializer=trading__pb2.MarketDataResponse.FromString,
                _registered_method=True)
        self.PlaceOrder = channel.unary_unary(
                '/trading.TradingService/PlaceOrder',
                request_serializer=trading__pb2.OrderRequest.SerializeToString,
                response_deserializer=trading__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/trading.TradingService/GetPositions',
                request_serializer=trading__pb2.PositionsRequest.SerializeToString,
                response_deserializer=trading__pb2.PositionsResponse.FromString,
                _registered_method=True)
        self.GetAccountInfo = channel.unary_unary(
                '/trading.TradingService/GetAccountInfo',
                request_serializer=trading__pb2.AccountRequest.SerializeToString,
                response_deserializer=trading__pb2.AccountResponse.FromString,
                _registered_method=True)
        self.StreamPrices = channel.unary_stream(
                '/trading.TradingService/StreamPrices',
                request_serializer=trading__pb2.StreamRequest.SerializeToString,
                response_deserializer=trading__pb2.PriceUpdate.FromString,
                _registered_method=True)
        self.ClosePosition = channel.unary_unary(
                '/trading.TradingService/ClosePosition',
                request_serializer=trading__pb2.ClosePositionRequest.SerializeToString,
                response_deserializer=trading__pb2.ClosePositionResponse.FromString,
                _registered_method=True)


class TradingServiceServicer(object):
    """==========================================
    Trading Service
    ==========================================
    """

    def GetMarketData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPrices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClosePosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMarketData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarketData,
                    request_deserializer=trading__pb2.MarketDataRequest.FromString,
                    response_serializer=trading__pb2.MarketDataResponse.SerializeToString,
            ),
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=trading__pb2.OrderRequest.FromString,
                    response_serializer=trading__pb2.OrderResponse.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=trading__pb2.PositionsRequest.FromString,
                    response_serializer=trading__pb2.PositionsResponse.SerializeToString,
            ),
            'GetAccountInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountInfo,
                    request_deserializer=trading__pb2.AccountRequest.FromString,
                    response_serializer=trading__pb2.AccountResponse.SerializeToString,
            ),
            'StreamPrices': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPrices,
                    request_deserializer=trading__pb2.StreamRequest.FromString,
                    response_serializer=trading__pb2.PriceUpdate.SerializeToString,
            ),
            'ClosePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.ClosePosition,
                    request_deserializer=trading__pb2.ClosePositionRequest.FromString,
                    response_serializer=trading__pb2.ClosePositionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trading.TradingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trading.TradingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradingService(object):
    """==========================================
    Trading Service
    ==========================================
    """

    @staticmethod
    def GetMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/GetMarketData',
            trading__pb2.MarketDataRequest.SerializeToString,
            trading__pb2.MarketDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/PlaceOrder',
            trading__pb2.OrderRequest.SerializeToString,
            trading__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/GetPositions',
            trading__pb2.PositionsRequest.SerializeToString,
            trading__pb2.PositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/GetAccountInfo',
            trading__pb2.AccountRequest.SerializeToString,
            trading__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/trading.TradingService/StreamPrices',
            trading__pb2.StreamRequest.SerializeToString,
            trading__pb2.PriceUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClosePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/ClosePosition',
            trading__pb2.ClosePositionRequest.SerializeToString,
            trading__pb2.ClosePositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
